# NodeUrl is the smpc node rpc url
# Gid is the subgroup id
# ThresHold is the group rule. It can be "2/3", "3/5", "4/6" ...
# KeyStore is the wallet account of the node of smpc
[Smpc]
NodeUrl = ""
Gid = ""
ThresHold   =""
KeyStore = "./config/smpc_k"

# The Server config
# DetectCount is the detect count when it request a sign to accept. The DetectTime is the time as seconds between two detect loops.
# AcceptTime is the check time as seconds with one loop.
# AcceptOverTime is the time as seconds. If smpc sign over this time, it should be not accepted.
[Server]
DetectCount = 60
DetectTime = 10
AcceptTime = 30
AcceptOverTime = 7200

# database driver is mysql 46768bacc61d97fe9d459fcb01181dcb6fae36f9
# the dabasebase name is "smpc" and the table to see the "readme"
[Db]
Host = "127.0.0.1"
Port = "3306"
DbName = "smpc"
Usr= "root"
Pwd= "851012"

[TxErrorRecord]
NodeRpc = "https://json-rpc.evm.testnet.shimmer.network/"
NodeWss = "wss://ws.json-rpc.evm.testnet.shimmer.network/"
Contract = "0xac1A077b6F9f52Bd225d3E43Bc4EdBb7F464bA31"
ScanEventType = 0
TimePeriod = 3600

# Tokens contain "ATOI", "IOTA", SMIOTA", "MATIC"
# Symbol is the unique
# ScanEventType, 0: listen event as websockt or mqtt; 1: scan block to get event logs.
# MultiSignType, 0 is contract multiSign, 2 is smpc multiSign
# MultiSignType = 0: PublicKey is null
# MultiSignType = 2: Contract and KeyStore is null
# MultiSignType = 2: Center
[[Tokens]]
Symbol = "SOON"
NodeRpc = "https://api.shimmer.network"
NodeWss = "https://api.shimmer.network"
ScanEventType = 0
MultiSignType = 3
PublicKey = "19ebbd746d8893dde6a7d7bf351269958532f0a8de24c0b012d1ae9b59019312"
Contract = "0884298fe9b82504d26ddb873dbd234a344c120da3a4317d8063dbcf96d356aa9d0100000000"
MinAmount = 1
KeyStore = "./config/smpc_k"

[[Tokens]]
Symbol = "sSOON"
NodeRpc = "https://json-rpc.evm.shimmer.network"
NodeWss = "wss://ws.json-rpc.evm.shimmer.network"
ScanEventType = 0
ScanMaxHeight = 1000
MultiSignType = 0
Contract = "0x39DEE4dFA8A94fB02F4004a38543c853F859d79E"
MinAmount = 1
KeyStore = "./config/smpc_k"


# Pairs is the bridge pair. 
# SrcToken to DestToken. They must be in the "Tokens".
[[Pairs]]
SrcToken = "SOON"
DestToken = "sSOON"