# NodeUrl is the node url of smpc
# Gid is the group id of "3"
# ThresHold is the group rule. It can be "2/3", "3/5", "4/6" ...
# KeyStore is the key of the node of smpc
[Smpc]
NodeUrl = "http://127.0.0.1:5871"
Gid = "e7fd1f3b48865f158dbccfcbc7d2af7ac7cab0783726ce43b0724b96cf83a8632cc637f6da880f06c4bb246b23fb96e0ef9a33b8dde72df7d1108294bf1aa33f"
ThresHold   ="2/3"
KeyStore = "./config/keystore"

# The Server config
# DetectCount is the detect count when it request a sign to accept. The DetectTime is the time as seconds between two detect loops.
# AcceptTime is the check time as seconds with one loop.
# AcceptOverTime is the time as seconds. If smpc sign over this time, it should be not accepted.
[Server]
DetectCount = 60
DetectTime = 10
AcceptTime = 30
AcceptOverTime = 7200

# database driver is mysql
# the dabasebase name is "smpc" and the table to see the "readme"
[Db]
Host = "127.0.0.1"
Port = "3306"
DbName = "smpc"
Usr="root"
Pwd="851012"

# Tokens contain "ATOI", "IOTA", SMIOTA", "MATIC"
# Symbol is the unique
# MultiSignType, 0 is contract multiSign, 2 is smpc multiSign
# MultiSignType = 0: PublicKey is null
# MultiSignType = 2: Contract and KeyStore is null
[[Tokens]]
Symbol = "ATOI"
#NodeUrl = "chrysalis-nodes.iota.org"
NodeUrl = "api.lb-0.h.chrysalis-devnet.iota.cafe"
MultiSignType = 2
#PublicKey = "715593d2c4dfa9bc5b2718e6a4c704b63cd3b62a81ca92b17ee3487daf3d593a"
PublicKey = "8c187002a32bf4143ae9260f3a08aca19ebea321d91f47fb7f8dfd2281f3d41a"
Contract = "null"
KeyStore = ""

[[Tokens]]
Symbol = "MATIC"
NodeUrl = "weathered-wild-county.matic-testnet.discover.quiknode.pro/459dfab8557cd04a86ea4c32b46164febe78449d/"
PublicKey = "null"
Contract = "0x361293435A9Bb241EcA9fb4517Fe3a2b242125cc"
KeyStore = "./config/k1"

[[Tokens]]
Symbol = "SMIOTA"
#NodeUrl = "weathered-wild-county.matic-testnet.discover.quiknode.pro/459dfab8557cd04a86ea4c32b46164febe78449d/"
NodeUrl = "api.sc.testnet.shimmer.network/evm/jsonrpc"
PublicKey = "null"
Contract = "0x2E5591820Dcd82Bf75B369665Ca81eA2Fe54BfB5"
KeyStore = "./config/k1"

[[Tokens]]
Symbol = "SMATIC"
#NodeUrl = "weathered-wild-county.matic-testnet.discover.quiknode.pro/459dfab8557cd04a86ea4c32b46164febe78449d/"
NodeUrl = "api.sc.testnet.shimmer.network/evm/jsonrpc"
PublicKey = "null"
Contract = "0x361293435A9Bb241EcA9fb4517Fe3a2b242125cc"
KeyStore = "./config/k1"

# Pairs is the bridge pair. 
# SrcToken to DestToken. They must beed in the "Tokens".
[[Pairs]]
SrcToken = "ATOI"
DestToken = "SMIOTA"
