# NodeUrl is the smpc node rpc url
# Gid is the subgroup id
# ThresHold is the group rule. It can be "2/3", "3/5", "4/6" ...
# KeyStore is the wallet account of the node of smpc
[Smpc]
NodeUrl = "http://127.0.0.1:5871"
Gid = "20b5e962f662e74eca9e63596c57bfce2b160aded631b3b613148ebd47696cfe710a2128de153c48d17e29fdf11230ba40d04b626dd32b2af6fcf5e93a0cc52e"
ThresHold   ="4/6"
KeyStore = "./config/smpc_k"

# The Server config
# DetectCount is the detect count when it request a sign to accept. The DetectTime is the time as seconds between two detect loops.
# AcceptTime is the check time as seconds with one loop.
# AcceptOverTime is the time as seconds. If smpc sign over this time, it should be not accepted.
[Server]
DetectCount = 60
DetectTime = 10
AcceptTime = 30
AcceptOverTime = 7200

# database driver is mysql 46768bacc61d97fe9d459fcb01181dcb6fae36f9
# the dabasebase name is "smpc" and the table to see the "readme"
[Db]
Host = "18.162.150.38"
Port = "3306"
DbName = "smpc"
Usr= "root"
Pwd= "851012"

[TxErrorRecord]
NodeRpc = "https://json-rpc.evm.testnet.shimmer.network/"
NodeWss = "wss://ws.json-rpc.evm.testnet.shimmer.network/"
Contract = "0xac1A077b6F9f52Bd225d3E43Bc4EdBb7F464bA31"
ScanEventType = 0
TimePeriod = 3600

# Tokens contain "ATOI", "IOTA", SMIOTA", "MATIC"
# Symbol is the unique
# ScanEventType, 0: listen event as websockt or mqtt; 1: scan block to get event logs.
# MultiSignType, 0 is contract multiSign, 2 is smpc multiSign
# MultiSignType = 0: PublicKey is null
# MultiSignType = 2: Contract and KeyStore is null
[[Tokens]]
Symbol = "ATOI"
NodeRpc = "https://api.lb-0.h.chrysalis-devnet.iota.cafe"
NodeWss = "wss://api.lb-0.h.chrysalis-devnet.iota.cafe/mqtt"
ScanEventType = 0
MultiSignType = 2
PublicKey = "b477a4b11a54a6a1a3aa792878f50b49e21536bf0bfdd0876ec99fae4e4bdb08"
MinAmount = 1000000

[[Tokens]]
Symbol = "MATIC"
NodeRpc = "https://polygon-mumbai.g.alchemy.com/v2/fXcphe9VsC6eWwEjRWaSz2ATxI_Sxn0K"
NodeWss = "wss://polygon-mumbai.g.alchemy.com/v2/fXcphe9VsC6eWwEjRWaSz2ATxI_Sxn0K"
ScanEventType = 0
ScanMaxHeight = 10000
MultiSignType = 0
Contract = "0x0F326747787Ec6894e9be2Af691d7451ea596660"
MinAmount = 1
KeyStore = "./config/smpc_k"

[[Tokens]]
Symbol = "WBTC"
NodeRpc = "https://polygon-mumbai.g.alchemy.com/v2/fXcphe9VsC6eWwEjRWaSz2ATxI_Sxn0K"
NodeWss = "wss://polygon-mumbai.g.alchemy.com/v2/fXcphe9VsC6eWwEjRWaSz2ATxI_Sxn0K"
ScanEventType = 0
ScanMaxHeight = 10000
MultiSignType = 0
Contract = "0xBF2F528b7d6b30Ede64a7a2D6C4819802831551b"
MinAmount = 1
KeyStore = "./config/smpc_k"

[[Tokens]]
Symbol = "sMIOTA"
NodeRpc = "https://json-rpc.evm.testnet.shimmer.network/"
NodeWss = "wss://ws.json-rpc.evm.testnet.shimmer.network/"
ScanEventType = 0
ScanMaxHeight = 1000
MultiSignType = 0
Contract = "0x1f7A07357e1E3e74A564fDeE8030f06F296AD540"
MinAmount = 1000000
KeyStore = "./config/smpc_k"

[[Tokens]]
Symbol = "sMATIC"
NodeRpc = "https://json-rpc.evm.testnet.shimmer.network/"
NodeWss = "wss://ws.json-rpc.evm.testnet.shimmer.network/"
ScanEventType = 0
ScanMaxHeight = 1000
MultiSignType = 0
Contract = "0xB6D0FBe198bf48c7E7dad8b457994a0dBac795Ef"
MinAmount = 1
KeyStore = "./config/smpc_k"

[[Tokens]]
Symbol = "sWTBC"
NodeRpc = "https://json-rpc.evm.testnet.shimmer.network/"
NodeWss = "wss://ws.json-rpc.evm.testnet.shimmer.network/"
ScanEventType = 0
ScanMaxHeight = 1000
MultiSignType = 0
Contract = "0x69499Cf6b0244AD7CEA28F6eeeb4EF4d8cd1Bc33"
MinAmount = 1
KeyStore = "./config/smpc_k"


# Pairs is the bridge pair. 
# SrcToken to DestToken. They must be in the "Tokens".
[[Pairs]]
SrcToken = "ATOI"
DestToken = "sMIOTA"

[[Pairs]]
SrcToken = "MATIC"
DestToken = "sMATIC"

[[Pairs]]
SrcToken = "WBTC"
DestToken = "sWBTC"